#!/bin/sh
cd ~/Zoro-Test/Zoro;
git pull;
echo 'Zoro project updated!';
cd ~/Zoro-Test/Zoro-Cli;
git pull;
echo 'Zoro-Cli project updated!';
cd ~/Zoro-Test/Zoro-Plugins;
git pull;
echo 'Zoro-Plugins project updated!';
cd ~/Zoro-Test/CowboyLib;
git pull;
echo 'CowboyLib project updated!';
cd ~/Zoro-Test/Zoro;
dotnet publish -c Release;
cd ~/Zoro-Test/Zoro-Plugins;
dotnet publish -c Release;
echo "publish success!";
cp -rf ~/Zoro-Test/Zoro-Plugins/SimplePolicy/bin/Release/netstandard2.0/SimplePolicy.dll ~/Zoro-Test/Zoro-Cli/zoro-cli/bin/Release/netcoreapp2.1/publish/Plugins/;
cp -rf ~/Zoro-Test/Zoro-Plugins/SimplePolicy/bin/Release/netstandard2.0/SimplePolicy ~/Zoro-Test/Zoro-Cli/zoro-cli/bin/Release/netcoreapp2.1/publish/Plugins/;
echo "copy SimplePolicy success!";
cp -r ~/Zoro-Shell/configs/appchain.json ~/Zoro-Test/Zoro-Cli/zoro-cli/bin/Release/netcoreapp2.1/publish/;
cp -r ~/Zoro-Shell/configs/protocol.json  ~/Zoro-Test/Zoro-Cli/zoro-cli/bin/Release/netcoreapp2.1/publish/;
echo "copy appchain protocol.json success!";
cp -a ~/Zoro-Test/Zoro-Cli/zoro-cli/bin/Release/netcoreapp2.1/publish/*  ~/Zoro-Test/Node1/;
cp -r ~/Zoro-Shell/configs/config1.json ~/Zoro-Test/Node1/config.json;
echo "create Node1 success!";
cp -rf ~/Zoro-Test/Zoro-Plugins/ApplicationLogs/bin/Release/netstandard2.0/ApplicationLogs.dll ~/Zoro-Test/Node1/Plugins/;
cp -rf ~/Zoro-Test/Zoro-Plugins/ApplicationLogs/bin/Release/netstandard2.0/ApplicationLogs ~/Zoro-Test/Node1/Plugins/;
echo "copy ApplicationLogs plugin success!";
cp -a ~/Zoro-Test/Zoro-Cli/zoro-cli/bin/Release/netcoreapp2.1/publish/*  ~/Zoro-Test/Node2/;
cp -r ~/Zoro-Shell/configs/config2.json ~/Zoro-Test/Node2/config.json;
echo "create Node2 success!";
cp -a ~/Zoro-Test/Zoro-Cli/zoro-cli/bin/Release/netcoreapp2.1/publish/*  ~/Zoro-Test/Node3/;
cp -r ~/Zoro-Shell/configs/config3.json ~/Zoro-Test/Node3/config.json;
echo "create Node3 success!";
cp -a ~/Zoro-Test/Zoro-Cli/zoro-cli/bin/Release/netcoreapp2.1/publish/*  ~/Zoro-Test/Node4/;
cp -r ~/Zoro-Shell/configs/config4.json ~/Zoro-Test/Node4/config.json;
echo "create Node4 success!";